### ISSUE TITLE
i keep getting this error

### ISSUE THREAD

**Issue by Guella** [mb1511/MUMmer-MUMi#1]
Traceback (most recent call last):
  File "./teste_mumi.py", line 4, in <module>
    print mumi.batch_run('/mnt/d/2018/teste_mumi', ext='fna', num_threads=16, k=19)
  File "/usr/local/lib/python2.7/dist-packages/mumi-0.1-py2.7.egg/mumi/__init__.py", line 46, in batch_run
    return '\n'.join(run(arg_list=n_map, k=k, cores=num_threads))
  File "/usr/local/lib/python2.7/dist-packages/mumi-0.1-py2.7.egg/mumi/multi.py", line 98, in wrap
    raise error_in_func
OSError: [Errno 2] No such file or directory

**Comment by mb1511** [comment]
This was likely due to a bug where the manually set mummer path was being overwritten, thus assuming it was on the system path when it's not. This problem was fixed a while ago for the batch_run() method and I've just fixed the single_run() method too. Sorry for the late reply, I've been mega busy with PhD work! Hope this helps.
